services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_HOST: ${PRS_POSTGRES_HOST}
      POSTGRES_PORT: ${PRS_POSTGRES_PORT}
      POSTGRES_USER: ${PRS_POSTGRES_USER}
      POSTGRES_PASS: ${PRS_POSTGRES_PASS}
      POSTGRES_DB:   ${PRS_POSTGRES_DB}
    volumes:
      - prs_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    networks:
      - application_network
  prs:
    build:
      context: ./prs
      dockerfile: Dockerfile
    container_name: prs
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: ${PRS_POSTGRES_HOST}
      POSTGRES_PORT: ${PRS_POSTGRES_PORT}
      POSTGRES_USER: ${PRS_POSTGRES_USER}
      POSTGRES_PASS: ${PRS_POSTGRES_PASS}
      POSTGRES_DB:   ${PRS_POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - application_network

networks:
  application_network:
    driver: bridge

volumes:
  prs_db_data: