services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${PRS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PRS_POSTGRES_DB}
    volumes:
      - prs_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5433:5432"
    networks:
      - application_network
  prs:
    build:
      context: ./prs
      dockerfile: Dockerfile
    container_name: prs
    ports:
      - "8080:8080"
    environment:
      PRS_DB_HOST: postgres
      PRS_DB_PORT: 5432
      PRS_DB_USER: ${PRS_POSTGRES_USER}
      PRS_DB_PASSWORD: ${PRS_POSTGRES_PASSWORD}
      PRS_DB_NAME: ${PRS_POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - application_network

networks:
  application_network:
    driver: bridge

volumes:
  prs_db_data: